### ISSUE TITLE
[/lex_node/lex_conversation]: lookup service failed with message [no provider]

### ISSUE THREAD

**Issue by rshah18** [aws-robotics/aws-robomaker-sample-application-voiceinteraction#41]
cant call the /lex_node/lex_conversation. please help 

---------------------------------------------------------------------------------------------    
def handle_text_input(self, request):
        
        user_input = request
        rospy.loginfo("Received text input {}".format(user_input))
        rospy.loginfo("audiodata coming up")
        print("audio arg passed")
        empty_audio_request = AudioData(data='')
        rospy.loginfo("audiodata passed")
        print("audio arg passed")
        lex_response = lex_service(content_type='text/plain; charset=utf-8',
                                      accept_type='text/plain; charset=utf-8',
                                      text_request=user_input,
                                      audio_request=empty_audio_request )
        rospy.loginfo("arguments passed")
        self.handle_lex_response(lex_response)
---------------------------------------------------------------------------------------------------
[rospy.client][INFO] 2019-08-13 18:53:52,109: init_node, name[/lex_conv], pid[25185]
[xmlrpc][INFO] 2019-08-13 18:53:52,109: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2019-08-13 18:53:52,110: ROS Slave URI: [http://ip-172-31-40-139:42928/]
[xmlrpc][INFO] 2019-08-13 18:53:52,110: Started XML-RPC server [http://ip-172-31-40-139:42928/]
[rospy.impl.masterslave][INFO] 2019-08-13 18:53:52,110: _ready: http://ip-172-31-40-139:42928/
[xmlrpc][INFO] 2019-08-13 18:53:52,110: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-08-13 18:53:52,111: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-08-13 18:53:52,210: registered with master
[rospy.rosout][INFO] 2019-08-13 18:53:52,210: initializing /rosout core topic
[rospy.rosout][INFO] 2019-08-13 18:53:52,213: connected to core topic /rosout
[rospy.simtime][INFO] 2019-08-13 18:53:52,215: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-08-13 18:53:52,220: Received text input go forward
[rospy.service][ERROR] 2019-08-13 18:53:52,221: [/lex_node/lex_conversation]: lookup service failed with message [no provider]
[rospy.core][INFO] 2019-08-13 18:53:52,222: signal_shutdown [atexit]
[rospy.impl.masterslave][INFO] 2019-08-13 18:53:52,225: atexit

**Comment by nburek** [comment]
Can you please provide more information about how you're starting the node and what action triggers this? 

It looks like it might possibly be an issue with us not calling `rospy.wait_for_service('/lex_node/lex_conversation')` before we attempt to call the service, so it might not be available yet if you send a message to quickly after startup.

**Comment by rshah18** [comment]
yes. it helped thank you @nburek

**Comment by nburek** [comment]
Reopening issue so that we can track correcting the source code in our repository as well. 

@rshah18 Thank you for confirming that adding the `wait_for_service` call mitigates the issue.

**Comment by AAlon** [comment]
Fix merged, closing.
