### ISSUE TITLE
ROS2 - python3-pyaudio not available from rosdep

### ISSUE THREAD

**Issue by timrobotson** [aws-robotics/aws-robomaker-sample-application-voiceinteraction#57]
ROS2 requires python3, the package python3-pyaudio [is available on Ubuntu 16.04+](https://packages.ubuntu.com/bionic/python3-pyaudio) however it's not yet in rosdep so rosdep install won't find it. 

Waiting on https://github.com/ros/rosdistro/pull/22623 to be merged to fix this issue. 

Until then if you want to use audio input/output you can install pyaudio by running `sudo apt install python3-pyaudio`

**Comment by mm318** [comment]
https://github.com/ros/rosdistro/pull/22623 has been merged. Closing this issue.
