### ISSUE TITLE
LexBot setup not setting resources

### ISSUE THREAD

**Issue by nburek** [aws-robotics/aws-robomaker-sample-application-voiceinteraction#8]
When launching this application using the one-click experience on the AWS console it is not properly setting the Lex Bot resources. This prevents the audio interface from working for the node. Specifically it is not doing the following two things: 

1) It does not set an output voice for the Lex Bot. 
2) It does not create the AWSServiceRoleForLexBots IAM Role. This usually created when a Lex Bot is created in the console.

**Comment by timrobotson** [comment]
The AWSServiceRoleForLexBots is only required when calling a Lambda function via Lex. So it's not neccessary when launching a one-click sample application. 

Output Voice is now being set correctly. Deploying the fix today.
